### ISSUE TITLE
Issues with Fubuki's palette

### ISSUE THREAD

**Issue by AyanamiRei1** [Makarew/Idol-Showdown-Studio#2]
For some unknown reason her 4H isn't using the palette fully.

![image](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/2bcd0470-7fb4-4e22-b31a-4b64932adcfb)

The palette is just for testing purposes

**Comment by AyanamiRei1** [comment]
Update I managed to fix it and now she actually uses the correct colours for her 4H

Before:
![image](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/60fd0f88-afe9-44c0-9a74-25b17bfc6741)

After:
![image](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/f3262b3f-2c66-4212-9070-c9226289d6e8)

And also here is tne modified sprites
![fubuki_gp](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/70fee078-bdc2-43a2-bd34-10f34c770915)

**Comment by Makarew** [comment]
The two missing colors will be added in the next update.

**Comment by Makarew** [comment]
Fixed in 0.6.1
