### ISSUE TITLE
Issues with Ayame 

### ISSUE THREAD

**Issue by AyanamiRei1** [Makarew/Idol-Showdown-Studio#3]
Changing all of her colours to a single colour should make her sprite be one colour and according to the program it IS but in game it isn't

![image](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/1cb3d0c7-e439-4deb-b384-1b84c55e403c)

![image](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/c92f7983-10e5-4f5e-a22a-d013270e778e)

And unlike Fubuki this isn't an issue to with her sprites being a slightly different colour.
![image](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/7ea1911d-12db-4f25-8fdc-f78e19b584b8)

**Comment by AyanamiRei1** [comment]
With my further testing with Fubuki's messed up missing colours it's just because the colours in the program and the colours that are actually on her sprites aren't the same.

![image](https://github.com/Makarew/Idol-Showdown-Studio/assets/25233407/7355d78c-e456-440f-9e3e-74d6245f7584)

Not a single edited image I only added the colour values for the messed up 4H into the in and out files

**Comment by Makarew** [comment]
The missing colors will be added in the next update.

**Comment by Makarew** [comment]
Fixed in 0.6.1
